service: xintern-companies-api
#app: your-app-name
#tenant: your-tenant-name

provider:
  name: aws
  runtime: nodejs10.x
  stage: master
  region: us-east-2
  environment:
    MONGO_URL: "${self:custom.tokens.MONGO_TEST}"
    TOKEN_SECRET: "${self:custom.tokens.TOKEN_SECRET}"

package:
  exclude:
    - tokens.yml

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  tokens: ${file(tokens.yml):${self:custom.stage}}
  customDomain: 
    domainName: 'api.xintern.co'
    basePath: 'company'
    stage: ${self:provider.stage}
    createRoute53Record: true

functions:
# ==================================
# COMPANY FUNCTIONS START
# ==================================
  addCompany:
    handler: company-handler.addCompany
    events:
      - http:
          path: /
          method: POST
          cors: true

  deleteCompany:
    handler: company-handler.deleteCompany
    events:
      - http:
          path: /{company_id}
          method: DELETE
          request:
            parameters:
              paths:
                company_id: true
          cors: true

  updateCompany:
    handler: company-handler.updateCompany
    events:
      - http:
          path: /{company_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                company_id: true
          cors: true

  getTopCompanies:
    handler: company-handler.getTopCompanies
    events:
      - http:
          path: top
          method: GET
          cors: true

  getAllCompanies:
    handler: company-handler.getAllCompanies
    events:
      - http:
          path: all
          method: GET
          cors: true
# ==================================
# END COMPANY FUNCTIONS
# ==================================