service: xintern-companies-api
#app: your-app-name
#tenant: your-tenant-name

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  environment:
    MONGO_URL: "${self:custom.tokens.MONGO_TEST}"
    TOKEN_SECRET: "${self:custom.tokens.TOKEN_SECRET}"

package:
  exclude:
    - tokens.yml

custom:
  stage: ${opt:stage, self:provider.stage}
  tokens: ${file(tokens.yml):${self:custom.stage}}

functions:
# ==================================
# COMPANY FUNCTIONS START
# ==================================
  addCompany:
    handler: company-handler.addCompany
    events:
      - http:
          path: company
          method: POST
          cors: true

  deleteCompany:
    handler: company-handler.deleteCompany
    events:
      - http:
          path: company/{company_id}
          method: DELETE
          request:
            parameters:
              paths:
                company_id: true
          cors: true

  updateCompany:
    handler: company-handler.updateCompany
    events:
      - http:
          path: review/{review_id}/company/{company_id}
          method: PATCH
          request:
            parameters:
              paths:
                review_id: true
                company_id: true
          cors: true

  getTopCompanies:
    handler: company-handler.getTopCompanies
    events:
      - http:
          path: companies/top
          method: GET
          cors: true

  getAllCompanies:
    handler: company-handler.getAllCompanies
    events:
      - http:
          path: company/all
          method: GET
          cors: true
# ==================================
# END COMPANY FUNCTIONS
# ==================================